version: "3.9"

services:
  backend:
    build: ./backend_democracy
    ports:
      - "8000:8000"
    volumes:
      - ./backend_democracy:/app
    depends_on:
      - mongo

  frontend:
    build: ./frontend_democracy
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_democracy:/app
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
